### ISSUE TITLE
Select code style and add to package.json

### ISSUE THREAD

**Issue by luke-john** [fendersperth/fendersbot#8]
I like the google jscs preset, but would be happy for any.

**Comment by kevincharm** [comment]
Also happy with any. Just to throw it out there; some other style guides include the [npm](https://docs.npmjs.com/misc/coding-style), [airbnb](https://github.com/airbnb/javascript), [meteor](https://github.com/meteor/meteor/wiki/Meteor-Style-Guide) style guides...

**Comment by karlbright** [comment]
I like the idea of having a style guide in place, but sometimes enforcing it via a tool can be annoying and super painful. I'm keen to use one, but we'd need some documentation around this and be open to changes I think.

We'd need to do bootstrap script for this to install the git commit hook, assuming that is what would be used. I'm keen to look at getting buildkite up and running for this project so i'll most likely pick that up soon and we can definitely lint the code as part of that once we have a style picked.

A few considerations at the moment, based on what this project is aimed to do.
- Semicolons should be used, because I think that is what most people coming in to this project will be used to and I think we need to keep barrier of entry quite low.
- Super simple postinstall hook to plug up that commit hook(if we use it) so people don't need to worry about that
- Users may be on windows so ensure that the script for git commit works across platforms
- Ensure that the code style takes ES6 in to account.
- I'm sure there are more we need to take in to account here but I just want to ensure we're making it super easy for others to come in to the project without having to type command after command.

**Comment by luke-john** [comment]
Most editors have packages that support it out of the box.

http://jscs.info/overview#friendly-packages

I'm uncertain as to the value of a commit hook.  For 'enforcement', we should just add a test.

**Comment by kevincharm** [comment]
I like the last few lines of the Google JS Style Guide (if we don't want to commit to a particular code style yet):

> BE CONSISTENT.
> If you're editing code, take a few minutes to look at the code around you and determine its style. If they use spaces around all their arithmetic operators, you should too. If their comments have little boxes of hash marks around them, make your comments have little boxes of hash marks around them too.

The airbnb style guide explicitly states some ES6 stuff like using arrow functions.

**Comment by luke-john** [comment]
From a quick squiz at the airbnb style guide it looks pretty neat.

It's a lot nicer to read than google's, so i'm swapping my +1 to airbnb.
